### ISSUE TITLE
STAR output lack xxx.Chimeric.out.sam

### ISSUE THREAD

**Issue by sunhaifeng-bio** [caochch/RIC-seq#1]
Hi,
The RIC-seq is a wonderful method to explore the RNA-RNA interactions. I believe an important role it will play in the future.
After download your article data and analyze it, I noticed an output of STAR by using:   

```
STAR --runMode alignReads \
--genomeDir $index \
--readFilesIn "$i".gz \
--readFilesCommand zcat \
--runThreadN 20 \
--outFileNamePrefix "$i". --outFilterMultimapNmax 100 --outSAMattributes All --alignIntronMin 1 \
--scoreGapNoncan -4 --scoreGapATAC -4 --chimSegmentMin 15 --chimJunctionOverhangMin 15 \
--alignSJoverhangMin 15 --alignSJDBoverhangMin 10 --alignSJstitchMismatchNmax 5 -1 5 5
```

which output a **SRR8632821_1.Chimeric.out.junction** rather than the **YourSample_read1_toGenomeChimeric.out.sam** decribed in your RIC-seq/1.find_pairTags_from_STAR_results/work.sh.

I tried use :

`perl 1.find_pairTags_from_STAR_results/precess_Chimeric_sam.pl  SRR8632821_1.Chimeric.out.junction > SRR8632821_1.Chimeric.out.junction.sam`

But get nothing.

It's there some wrong in my code? Or where need I modify it ? 

Thanks in advance for your reply.

Best wishes

Haifeng Sun
NanJing Medical University
2020.06.29

**Comment by caochch** [comment]
What's your STAR version? STAR will output xxx.chimeric.sam as described in its manual.

The work.sh is just what I used in my analysis.

**Comment by sunhaifeng-bio** [comment]
Hi,
My STAR version is 2.7.3a. And Ubuntu 18 system.

```
$ STAR --version
2.7.3a
```

```
for i in SRR8632820 \
do  \
echo $i .... \
STAR --runMode alignReads \
--genomeDir $index \
--readFilesIn "$i"_1.gz \
--readFilesCommand zcat \
--runThreadN 20 \
--outFileNamePrefix "$i"_1. \
--outFilterMultimapNmax 100 \
--outSAMattributes All --alignIntronMin 1 --scoreGapNoncan -4 \
--scoreGapATAC -4 --chimSegmentMin 15 \
--chimJunctionOverhangMin 15 --alignSJoverhangMin 15 \
--alignSJDBoverhangMin 10 \
--alignSJstitchMismatchNmax 5 -1 5 5
done

# SRR8632820 ....
# Jul 13 17:26:51 ..... started STAR run
# Jul 13 17:26:51 ..... loading genome
# Jul 13 17:29:40 ..... started mapping
# Jul 13 17:36:01 ..... finished mapping
# Jul 13 17:36:04 ..... finished successfully
```

```
ls
SRR8632820_1.gz
SRR8632820_1.Aligned.out.sam
SRR8632820_1.Chimeric.out.junction
SRR8632820_1.Log.final.out
SRR8632820_1.Log.out
SRR8632820_1.Log.progress.out
SRR8632820_1.SJ.out.tab
```

I attached the files of log here. Thank you in advance!

Looking for your reply.

Haifeng Sun


[SRR8632820_1.Log.final.out.txt](https://github.com/caochch/RIC-seq/files/4911652/SRR8632820_1.Log.final.out.txt)
[SRR8632820_1.Log.out.txt](https://github.com/caochch/RIC-seq/files/4911654/SRR8632820_1.Log.out.txt)
[SRR8632820_1.Log.progress.out.txt](https://github.com/caochch/RIC-seq/files/4911655/SRR8632820_1.Log.progress.out.txt)

**Comment by caochch** [comment]
I used your command (the identical parameters) and my reads.fq:

STAR --runMode alignReads --genomeDir index.dir --readFilesIn read.fq --runThreadN 20 --outFileNamePrefix test --outFilterMultimapNmax 100 --outSAMattributes All --alignIntronMin 1 --scoreGapNoncan -4 --scoreGapATAC -4 --chimSegmentMin 15 --chimJunctionOverhangMin 15 --alignSJoverhangMin 15 --alignSJDBoverhangMin 10 --alignSJstitchMismatchNmax 5 -1 5 5. 

I can successfully get the chimeric.sam and I could not figure out why.

Maybe you can try another version of STAR (my version is STAR_2.5.2b).

**Comment by sunhaifeng-bio** [comment]
Thanks, I will try
