### ISSUE TITLE
How to clip the poly(N) tails at the 3′ end 

### ISSUE THREAD

**Issue by QianzhaoJ** [caochch/RIC-seq#2]
Hi,
   RIC-seq technology is a helpful method to profile global RNA-RNA interactions, and I am very interested in the results showing published paper. So I downloaded RIC-seq data from the GEO database and tried the downstream analysis.
   I have trimmed adapters and PCR duplicates as paper described, but confused about the steps about clipping the poly(N) tails. I noticed the software `cutadapt`, but about the parameter settings, could you give me some suggestions?
   Thanks in advance!

Best wishes 
Qianzhao

**Comment by caochch** [comment]
The command looks like this: cutadapt -j 10 -b A{100} -b C{100} -b G{100} -b T{100} ....
