### ISSUE TITLE
How to generate  hicFiles

### ISSUE THREAD

**Issue by QianzhaoJ** [caochch/RIC-seq#3]
Hi,
   I have downloaded RIC-seq data from the GEO database and tried the downstream analysis as described in your github.
   I have successfully finished step1 `find_pairTags_from_STAR_results` and got interaction Samfiles, but when I tried to convert the Samfiles to hicFiles using the scripts in `2.construct_hicFiles_for_rRNA` :
  
> perl $RIC/sam_to_loops.pl $sam chr1 0 100000000 > $result/chr1_loops.txt &&
   perl $RIC/interaction_from_loop_to_JuiceBox.pl $result/chr1_loops.txt > $result/chr1_loops.list &&
   cat $result/chr1_loops.list | sort -k3,3 -k7,7 > $result/chr1_loops.sorted.list &&
   java -jar $juice pre -r 1,2,5,10,20,50 $result/chr1_loops.sorted.list $result/${sample}.chr1.RR.hic $chr1_size &&

Finally, I got a very small hicFiles (just only a few kb) and I can't open it in juicebox. There is the warnings from juicertools: 

> WARN [2021-01-05T02:55:16,293]  [Globals.java:138] [main]  Development mode is enabled
Not including fragment map
Start preprocess
Writing header
Writing body
.java.lang.IllegalArgumentException: Illegal initial capacity: -1809845095
	at java.util.HashMap.<init>(HashMap.java:448)
	at java.util.HashMap.<init>(HashMap.java:467)
	at java.util.LinkedHashMap.<init>(LinkedHashMap.java:359)
	at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.<init>(Preprocessor.java:1578)
	at juicebox.tools.utils.original.Preprocessor$MatrixPP.<init>(Preprocessor.java:1450)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:765)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:419)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:121)
	at juicebox.tools.HiCTools.main(HiCTools.java:96)

and my juicertools version is `juicer_tools_1.13.02.jar`.

I don't know what happened, Could you give me some advice?

Here is the small hicFile:
[chr1.zip](https://github.com/caochch/RIC-seq/files/5766346/chr1.zip)
Here is the looplist file:
[chr1_loops.zip](https://github.com/caochch/RIC-seq/files/5766348/chr1_loops.zip)

Thanks in advance!

Bests,
Qianzhao

**Comment by caochch** [comment]
Using the following command, I build the hic file successfully with the loop list file provided by you.
java -jar /home/caochch/software/JuiceBox/juicebox_tools.jar pre -r 10000 chr1_loops.list chr1.hic hg19.chrom.sizes

Please check your command and your chr.size file carefully.
