### ISSUE TITLE
can you provide the bed file (which is showed by IGV)

### ISSUE THREAD

**Issue by GaoLi1997** [caochch/RIC-seq#4]
I read the paper "RIC-seq for global in situ profiling of RNA–RNA spatial interactions", and I want to see the RNA interaction. But I just can download the .hic file. I have no idea to chage the .hic file to a readable file.

If you can provide the chimeric reads infomation  in readable way, I will really apreciate.

**Comment by caochch** [comment]
You cau use juicer tools to dump data from hic files (see https://github.com/aidenlab/juicer/wiki/Juicer-Tools-Quick-Start)
