### ISSUE TITLE
Which is paritag.sam in 2.construct_hicFiles_for_rRNA?

### ISSUE THREAD

**Issue by PonderLi** [caochch/RIC-seq#5]
hello, Cao! Thanks to your great work! I met an problem that which is paritag.sam in 2.construct_hicFiles_for_rRNA? There is no pairtag.sam in the result of step1! Looking forward to your reply!

**Comment by LianzePuppet** [comment]
> hello, Cao! Thanks to your great work! I met an problem that which is paritag.sam in 2.construct_hicFiles_for_rRNA? There is no pairtag.sam in the result of step1! Looking forward to your reply!

I also have this question
